### ISSUE TITLE
Comment section doesn't work

### ISSUE THREAD

**Issue by Filonczuk** [t3rmian/react-static-teapot#2]
![image](https://user-images.githubusercontent.com/33152430/63148579-e9b58b00-c001-11e9-9f6c-c37ebaaa6ac9.png)

**Comment by terlecki-rsi** [comment]
Thanks for reporting, forgot to install the _[utterances](https://github.com/apps/utterances)_ app in GitHub for a specific repository. Should be fixed now.

**Comment by t3rmian** [comment]
Thanks for reporting, forgot to install the utterances app in GitHub for a specific repository. Should be fixed now.
